name: Elixir CI

on: [push, pull_request]

env:
  MIX_ARCHIVES: /home/circleci/project/.mix/archives
  MIX_HOME: /home/circleci/project/.mix

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: project
          path: .

  deps:
    needs: [checkout]
    runs-on: ubuntu-latest
    container: circleci/elixir:1.11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: project
      - run: mix local.hex --force --if-missing
      - run: mix local.rebar --force --if-missing
      - run: mix deps.get
      - uses: actions/upload-artifact@v2
        with:
          name: deps
          path: .

  build:
    needs: [deps]
    runs-on: ubuntu-latest
    container: circleci/elixir:1.11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deps
      - run: mix compile --warnings-as-errors
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: _build

  format:
    needs: [deps]
    runs-on: ubuntu-latest
    container: circleci/elixir:1.11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deps
      - run: mix format --check-formatted

  dialyzer:
    needs: [deps]
    runs-on: ubuntu-latest
    container: circleci/elixir:1.11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deps
      - run: mix dialyzer

  credo:
    needs: [deps]
    runs-on: ubuntu-latest
    container: circleci/elixir:1.11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deps
      - run: mix credo

  test:
    needs: [deps]
    runs-on: ubuntu-latest
    container: circleci/elixir:1.11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deps
      - run: mix test
